import { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  CheckCircle2,
  Database,
  MapPin,
  RefreshCw,
  Target,
} from "lucide-react";
import {
  PolarAngleAxis,
  PolarGrid,
  Radar,
  RadarChart,
  ResponsiveContainer,
  Tooltip,
} from "recharts";
import {
  getProjectGapAnalysis,
  getWardAnalysis,
  runWardAnalysis,
} from "../api/client.js";
import { WardSelector } from "./map/WardSelector.jsx";

const dimensions = [
  ["healthcare_score", "Healthcare"],
  ["education_score", "Education"],
  ["mobility_score", "Mobility"],
  ["environment_score", "Environment"],
  ["green_space_score", "Green space"],
  ["infrastructure_score", "Infrastructure"],
];

const summaryScores = [
  ["urban_health_score", "Urban health", "Quality and service coverage"],
  [
    "infrastructure_gap_score",
    "Infrastructure gap",
    "Higher means a larger deficit",
  ],
  [
    "population_need_score",
    "Population need",
    "Demand from density and growth",
  ],
];

const readable = (value) => String(value).replaceAll("_", " ");
const pendingInitialAnalyses = new Map();

async function loadOrCreateAnalysis(wardId) {
  try {
    return await getWardAnalysis(wardId);
  } catch (requestError) {
    if (requestError.response?.data?.error?.code !== "ANALYSIS_NOT_FOUND")
      throw requestError;
    if (!pendingInitialAnalyses.has(wardId)) {
      const request = runWardAnalysis(wardId).finally(() =>
        pendingInitialAnalyses.delete(wardId),
      );
      pendingInitialAnalyses.set(wardId, request);
    }
    return pendingInitialAnalyses.get(wardId);
  }
}

function AnalysisSkeleton() {
  return (
    <div className="analysis-state" role="status">
      <span className="loader" />
      <h3>Calculating ward conditions</h3>
      <p>Applying the explainable scoring model to current urban records…</p>
    </div>
  );
}

function ScoreCard({ label, note, score }) {
  return (
    <div className="analysis-score-card">
      <span>{label}</span>
      <strong>
        {score}
        <small>/100</small>
      </strong>
      <div
        aria-label={`${label}: ${score} out of 100`}
        className="analysis-meter"
      >
        <i style={{ width: `${score}%` }} />
      </div>
      <p>{note}</p>
    </div>
  );
}

function WardUrbanGapAnalysis({ cityId, wards = [] }) {
  const [selectedWardId, setSelectedWardId] = useState(wards[0]?.id ?? null);
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const [retryCount, setRetryCount] = useState(0);

  useEffect(() => {
    setSelectedWardId(wards[0]?.id ?? null);
    setAnalysis(null);
  }, [cityId, wards]);

  useEffect(() => {
    if (!selectedWardId) return undefined;
    let active = true;
    setLoading(true);
    setError("");
    loadOrCreateAnalysis(selectedWardId)
      .then((result) => {
        if (active) setAnalysis(result);
      })
      .catch((requestError) => {
        if (active)
          setError(
            requestError.response?.data?.error?.message ??
              "Unable to load this ward analysis",
          );
      })
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => {
      active = false;
    };
  }, [selectedWardId, retryCount]);

  const chartData = useMemo(
    () =>
      dimensions.map(([key, label]) => ({
        dimension: label,
        score: analysis?.[key] ?? 0,
        target: 75,
      })),
    [analysis],
  );

  const refresh = async () => {
    setRefreshing(true);
    setError("");
    try {
      setAnalysis(await runWardAnalysis(selectedWardId));
      window.dispatchEvent(
        new CustomEvent("citymind:analysis-updated", {
          detail: { wardId: selectedWardId },
        }),
      );
    } catch (requestError) {
      setError(
        requestError.response?.data?.error?.message ??
          "Unable to recalculate this ward",
      );
    } finally {
      setRefreshing(false);
    }
  };

  if (!wards.length) {
    return (
      <article className="panel analysis-panel">
        <div className="analysis-state">
          <Database />
          <h3>No wards available</h3>
          <p>Add ward and urban records before running an analysis.</p>
        </div>
      </article>
    );
  }

  return (
    <article className="panel analysis-panel">
      <div className="panel-heading analysis-heading">
        <div>
          <p className="eyebrow">Explainable urban diagnostics</p>
          <h2>AI Urban Gap Analysis</h2>
          <p>
            Scores are calculated by CityMind’s deterministic model—not
            generated by AI.
          </p>
        </div>
        <div className="analysis-actions">
          <WardSelector
            wards={wards}
            selectedWardId={selectedWardId}
            onSelect={setSelectedWardId}
          />
          <button
            aria-label="Recalculate analysis"
            disabled={!analysis || refreshing}
            onClick={refresh}
            type="button"
          >
            <RefreshCw className={refreshing ? "spinning" : ""} size={14} />
            {refreshing ? "Calculating" : "Recalculate"}
          </button>
        </div>
      </div>

      {loading && <AnalysisSkeleton />}
      {error && !loading && (
        <div className="analysis-state error">
          <AlertTriangle />
          <h3>Analysis unavailable</h3>
          <p>{error}</p>
          <button
            onClick={() => setRetryCount((count) => count + 1)}
            type="button"
          >
            Try again
          </button>
        </div>
      )}
      {analysis && !loading && !error && (
        <>
          <div className="analysis-context">
            <div>
              <span>Selected area</span>
              <strong>{analysis.ward.name}</strong>
              <small>{analysis.ward.ward_code}</small>
            </div>
            <div
              className={`priority-badge ${analysis.overall_priority.toLowerCase()}`}
            >
              <Target size={15} />
              <span>Overall priority</span>
              <strong>{analysis.overall_priority}</strong>
            </div>
          </div>
          <div className="analysis-summary-grid">
            {summaryScores.map(([key, label, note]) => (
              <ScoreCard
                key={key}
                label={label}
                note={note}
                score={analysis[key]}
              />
            ))}
            <div
              className={`analysis-priority-card ${analysis.overall_priority.toLowerCase()}`}
            >
              <span>Planning priority</span>
              <strong>{analysis.overall_priority}</strong>
              <p>Priority index {analysis.priority_score}/100</p>
              <small>
                Gap 55% · Population need 35% · Environmental deficit 10%
              </small>
            </div>
          </div>

          <div className="analysis-detail-grid">
            <section className="analysis-radar-card">
              <div className="analysis-card-title">
                <div>
                  <p className="eyebrow">Six-dimension profile</p>
                  <h3>Ward performance</h3>
                </div>
                <span>
                  <i /> Planning target 75
                </span>
              </div>
              <div className="analysis-radar">
                <ResponsiveContainer width="100%" height="100%">
                  <RadarChart data={chartData} outerRadius="68%">
                    <PolarGrid stroke="#29423a" />
                    <PolarAngleAxis
                      dataKey="dimension"
                      tick={{ fill: "#8da29b", fontSize: 10 }}
                    />
                    <Radar
                      dataKey="target"
                      fill="#d9e5e1"
                      fillOpacity={0.035}
                      stroke="#6f817b"
                      strokeDasharray="4 4"
                    />
                    <Radar
                      dataKey="score"
                      fill="#45dfa5"
                      fillOpacity={0.24}
                      stroke="#5ce5b1"
                      strokeWidth={2}
                    />
                    <Tooltip
                      content={({ active, payload }) =>
                        active && payload?.length ? (
                          <div className="chart-tooltip">
                            <b>{payload[0].payload.dimension}</b>
                            <span>
                              Score {payload[1]?.value ?? payload[0].value}/100
                            </span>
                          </div>
                        ) : null
                      }
                    />
                  </RadarChart>
                </ResponsiveContainer>
              </div>
            </section>

            <section className="analysis-dimensions-card">
              <div className="analysis-card-title">
                <div>
                  <p className="eyebrow">Coverage scores</p>
                  <h3>Measured dimensions</h3>
                </div>
                <span>
                  {analysis.data_quality.completeness_percent}% data complete
                </span>
              </div>
              <div className="dimension-list">
                {dimensions.map(([key, label]) => (
                  <div key={key}>
                    <span>{label}</span>
                    <div>
                      <i style={{ width: `${analysis[key]}%` }} />
                    </div>
                    <strong>{analysis[key]}</strong>
                  </div>
                ))}
              </div>
            </section>
          </div>

          <div className="analysis-bottom-grid">
            <section className="attention-card">
              <div className="analysis-card-title">
                <div>
                  <p className="eyebrow">Deterministic findings</p>
                  <h3>Why this area needs attention</h3>
                </div>
                <CheckCircle2 size={18} />
              </div>
              <ul>
                {analysis.reasons.map((reason) => (
                  <li key={reason}>{reason}</li>
                ))}
              </ul>
            </section>
            <section className="evidence-card">
              <div className="analysis-card-title">
                <div>
                  <p className="eyebrow">Source evidence</p>
                  <h3>Inputs used</h3>
                </div>
                <Database size={17} />
              </div>
              <dl>
                <div>
                  <dt>Population</dt>
                  <dd>{analysis.evidence.population.toLocaleString()}</dd>
                </div>
                <div>
                  <dt>Density</dt>
                  <dd>
                    {analysis.evidence.population_density.toLocaleString()}/km²
                  </dd>
                </div>
                <div>
                  <dt>Hospitals / schools / parks</dt>
                  <dd>
                    {analysis.evidence.hospitals} / {analysis.evidence.schools}{" "}
                    / {analysis.evidence.parks}
                  </dd>
                </div>
                <div>
                  <dt>Road coverage</dt>
                  <dd>{analysis.evidence.road_density} km/km²</dd>
                </div>
                <div>
                  <dt>Air quality index</dt>
                  <dd>{analysis.evidence.air_quality_index ?? "Missing"}</dd>
                </div>
                <div>
                  <dt>Green cover</dt>
                  <dd>{analysis.evidence.green_cover_percent ?? "Missing"}%</dd>
                </div>
              </dl>
              {analysis.data_quality.missing_fields.length > 0 && (
                <p className="data-warning">
                  Missing inputs scored as zero:{" "}
                  {analysis.data_quality.missing_fields
                    .map(readable)
                    .join(", ")}
                  .
                </p>
              )}
            </section>
          </div>
          <p className="analysis-footnote">
            Model v{analysis.scoring_version} · Stored analysis #
            {analysis.analysis_id} · Generated by deterministic backend
            calculations
          </p>
        </>
      )}
    </article>
  );
}

const confidenceClass = (value) =>
  `confidence-chip ${String(value).toLowerCase()}`;

function ProjectUrbanGapAnalysis({
  initialAnalysis = null,
  onAnalysis,
  planningProject,
  planningProjectId,
}) {
  const [analysis, setAnalysis] = useState(initialAnalysis);
  const [loading, setLoading] = useState(!initialAnalysis);
  const [error, setError] = useState("");
  const [refreshKey, setRefreshKey] = useState(0);
  const [benchmarkScale, setBenchmarkScale] = useState(1);

  useEffect(() => {
    let active = true;
    setLoading(true);
    setError("");
    getProjectGapAnalysis(planningProjectId, benchmarkScale)
      .then((result) => {
        if (!active) return;
        setAnalysis(result);
        onAnalysis?.(result);
        window.dispatchEvent(
          new CustomEvent("citymind:project-gap-analysis", { detail: result }),
        );
      })
      .catch((requestError) => {
        if (active)
          setError(
            requestError.response?.data?.error?.message ??
              "Unable to analyze this planning area",
          );
      })
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => {
      active = false;
    };
  }, [benchmarkScale, onAnalysis, planningProjectId, refreshKey]);

  const viewOnMap = (area) => {
    window.dispatchEvent(
      new CustomEvent("citymind:focus-gap-area", { detail: { area } }),
    );
    const mapElement = document.getElementById("map");
    if (typeof mapElement?.scrollIntoView === "function") {
      mapElement.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  if (loading)
    return (
      <article className="panel analysis-panel">
        <AnalysisSkeleton />
      </article>
    );
  if (error)
    return (
      <article className="panel analysis-panel">
        <div className="analysis-state error">
          <AlertTriangle />
          <h3>Project analysis unavailable</h3>
          <p>{error}</p>
          <button
            onClick={() => setRefreshKey((value) => value + 1)}
            type="button"
          >
            Try again
          </button>
        </div>
      </article>
    );

  const plannedByKey = new Map(
    (analysis.planned_scenario?.categories ?? []).map((category) => [
      category.key,
      category,
    ]),
  );

  return (
    <article className="panel analysis-panel project-gap-report">
      <div className="panel-heading analysis-heading">
        <div>
          <p className="eyebrow">Project coverage gap report</p>
          <h2>What does this planning area currently need?</h2>
          <p>
            {planningProject.name} ·{" "}
            {planningProject.project_type.replaceAll("_", " ")}
          </p>
        </div>
        <div className="analysis-actions">
          <label>
            Service standard
            <select 
              aria-label="Service standard"
              onChange={(event) =>
                setBenchmarkScale(Number(event.target.value))
              }
              value={benchmarkScale}
            >
              <option value="0.8">Essential</option>
              <option value="1">Standard</option>
              <option value="1.25">Ambitious</option>
            </select>
          </label>
          <button
            aria-label="Refresh project gap analysis"
            onClick={() => setRefreshKey((value) => value + 1)}
            type="button"
          >
            <RefreshCw size={14} />
            Refresh evidence
          </button>
        </div>
      </div>

      <section className="project-gap-overview">
        <div>
          <span>Overall service gap</span>
          <strong>
            {analysis.overview.overall_gap_percent}
            <small>%</small>
          </strong>
          <b className={analysis.overview.status.toLowerCase()}>
            {analysis.overview.status}
          </b>
          {analysis.planned_scenario && (
            <small>
              Planned: {analysis.planned_scenario.overview.overall_gap_percent}%
              gap ({analysis.planned_scenario.gap_change >= 0 ? "−" : "+"}
              {Math.abs(analysis.planned_scenario.gap_change)} points)
            </small>
          )}
        </div>
        <div>
          <span>Planning population</span>
          <strong>{Number(analysis.population.value).toLocaleString()}</strong>
          <i className={confidenceClass(analysis.population.confidence)}>
            {analysis.population.confidence}
          </i>
        </div>
        <div>
          <span>Critical categories</span>
          <strong>{analysis.overview.critical_categories}</strong>
          <small>
            {analysis.overview.high_categories} high-priority categories
          </small>
        </div>
        <div>
          <span>Mapped critical areas</span>
          <strong>{analysis.overview.mapped_critical_areas}</strong>
          <small>Service-distance findings</small>
        </div>
      </section>

      <section className="project-gap-categories">
        <div className="analysis-card-title">
          <div>
            <p className="eyebrow">Gap by category</p>
            <h3>Coverage against planning benchmarks</h3>
          </div>
          <span>Coverage shown from 0–100%</span>
        </div>
        <div className="coverage-gap-grid">
          {analysis.categories.map((category) => (
            <article
              className={`coverage-gap-card ${category.gap.toLowerCase()}`}
              key={category.key}
            >
              <header>
                <div>
                  <span>{category.category}</span>
                  <strong>{category.coverage_percent}% coverage</strong>
                  {plannedByKey.has(category.key) && (
                    <small>
                      {plannedByKey.get(category.key).coverage_percent}% if
                      proposals are implemented
                    </small>
                  )}
                </div>
                <b>{category.gap} gap</b>
              </header>
              <div
                aria-label={`${category.category}: ${category.coverage_percent}% coverage`}
                className="coverage-gap-meter"
              >
                <i style={{ width: `${category.coverage_percent}%` }} />
              </div>
              <dl>
                <div>
                  <dt>Required</dt>
                  <dd>
                    {category.required} {category.unit}
                  </dd>
                </div>
                <div>
                  <dt>Inside boundary</dt>
                  <dd>{category.existing_inside}</dd>
                </div>
                <div>
                  <dt>Surrounding</dt>
                  <dd>{category.surrounding_available}</dd>
                </div>
                <div>
                  <dt>Missing</dt>
                  <dd>{category.missing}</dd>
                </div>
              </dl>
              {category.capacity && (
                <p>
                  Capacity gap:{" "}
                  <strong>{category.capacity.gap.toLocaleString()}</strong> ·
                  Potentially overloaded facilities:{" "}
                  {category.capacity.overloaded_facilities}
                </p>
              )}
              <footer>
                <span>Service radius {category.service_radius_km} km</span>
                <i
                  className={confidenceClass(
                    category.confidence.existing_supply,
                  )}
                >
                  MEASURED
                </i>
                <i
                  className={confidenceClass(
                    category.confidence.required_supply,
                  )}
                >
                  ESTIMATED
                </i>
              </footer>
            </article>
          ))}
        </div>
      </section>

      {analysis.block_analysis?.blocks?.length > 0 && (
        <section className="block-gap-section">
          <div className="analysis-card-title">
            <div>
              <p className="eyebrow">Boundary planning units</p>
              <h3>Gap Analysis by Block</h3>
            </div>
            <span>Population values are planning assumptions</span>
          </div>
          <div className="block-gap-grid">
            {analysis.block_analysis.blocks.map((item) => (
              <article key={item.block.id}>
                <header>
                  <div>
                    <strong>{item.block.name}</strong>
                    <span>{item.block.land_use}</span>
                  </div>
                  <b>{item.score}/100</b>
                </header>
                <dl>
                  <div>
                    <dt>People living</dt>
                    <dd>{item.population.toLocaleString()}</dd>
                  </div>
                  <div>
                    <dt>Households</dt>
                    <dd>{item.households.toLocaleString()}</dd>
                  </div>
                  <div>
                    <dt>Density</dt>
                    <dd>{item.population_density_per_acre}/acre</dd>
                  </div>
                </dl>
                <div className="block-gap-tags">
                  {item.gaps.length ? (
                    item.gaps.slice(0, 4).map((gap) => (
                      <span
                        className={gap.priority.toLowerCase()}
                        key={gap.category}
                      >
                        {gap.category.replaceAll("_", " ")} · {gap.gap_score}%
                        gap
                      </span>
                    ))
                  ) : (
                    <span>No critical gaps</span>
                  )}
                </div>
              </article>
            ))}
          </div>
        </section>
      )}

      <div className="project-gap-lower-grid">
        <section className="critical-area-card">
          <div className="analysis-card-title">
            <div>
              <p className="eyebrow">Map visualization</p>
              <h3>Critical Areas</h3>
            </div>
            <MapPin size={18} />
          </div>
          {analysis.critical_areas.length ? (
            <div className="critical-area-list">
              {analysis.critical_areas.slice(0, 10).map((area) => (
                <article key={area.id}>
                  <i className={area.severity.toLowerCase()} />
                  <div>
                    <strong>
                      {area.site} · {area.category}
                    </strong>
                    <p>{area.reason}</p>
                    <span className={confidenceClass(area.confidence)}>
                      {area.confidence}
                    </span>
                  </div>
                  <button onClick={() => viewOnMap(area)} type="button">
                    <MapPin size={12} />
                    View on map
                  </button>
                </article>
              ))}
            </div>
          ) : (
            <p className="project-gap-empty">
              No critical service-distance areas were identified from the
              available coordinates.
            </p>
          )}
        </section>

        <section className="priority-area-card">
          <div className="analysis-card-title">
            <div>
              <p className="eyebrow">Action sequence</p>
              <h3>Priority Areas</h3>
            </div>
            <Target size={18} />
          </div>
          <ol>
            {analysis.priority_areas.map((category) => (
              <li key={category.key}>
                <b>{category.rank}</b>
                <div>
                  <strong>{category.category}</strong>
                  <span>
                    {category.missing} {category.unit} missing now
                  </span>
                </div>
                <em>{category.gap_percent}% gap</em>
              </li>
            ))}
          </ol>
          <div className="future-capacity-note">
            <span className={confidenceClass("SIMULATED")}>SIMULATED</span>
            <p>
              Future requirements use the {analysis.population.planning_horizon}
              -year horizon. Projected population:{" "}
              {Number(analysis.population.projected_value).toLocaleString()}.
            </p>
          </div>
        </section>
      </div>

      <section className="confidence-principle">
        <Database size={16} />
        <div>
          <strong>Data confidence</strong>
          <p>
            <span className={confidenceClass("MEASURED")}>MEASURED</span> mapped
            records{" "}
            <span className={confidenceClass("ESTIMATED")}>ESTIMATED</span>{" "}
            service benchmarks and catchments{" "}
            <span className={confidenceClass("SIMULATED")}>SIMULATED</span>{" "}
            future capacity
          </p>
          <p>
            Current coverage counts approved assets only. The planned preview
            simulates all non-rejected project proposals.
          </p>
        </div>
      </section>
      {analysis.horizon_scenarios?.length > 0 && (
        <section className="candidate-comparison">
          <div className="analysis-card-title">
            <div>
              <p className="eyebrow">Demand scenarios</p>
              <h3>5 / 10 / 20 / 30-year requirements</h3>
            </div>
            <span className={confidenceClass("SIMULATED")}>SIMULATED</span>
          </div>
          <div className="scenario-grid">
            {analysis.horizon_scenarios.map((scenario) => (
              <article key={scenario.years}>
                <span>{scenario.years}-year</span>
                <strong>{Number(scenario.population).toLocaleString()}</strong>
                <small>people</small>
                <p>
                  {scenario.requirements.HOSPITAL} hospitals ·{" "}
                  {scenario.requirements.SCHOOL} schools ·{" "}
                  {scenario.requirements.PARK} parks
                </p>
              </article>
            ))}
          </div>
        </section>
      )}
      <p className="analysis-footnote">
        Project gap model v{analysis.methodology.version} · Deterministic
        service-distance analysis · Surrounding facilities contribute{" "}
        {analysis.methodology.surrounding_asset_contribution * 100}% estimated
        capacity
      </p>
    </article>
  );
}

export function UrbanGapAnalysis(props) {
  return props.planningProjectId ? (
    <ProjectUrbanGapAnalysis {...props} />
  ) : (
    <WardUrbanGapAnalysis {...props} />
  );
}
